name: crypto_stats
description: An application that shows current prices for famous cryptocurrencies.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: 2.5.0-5.2.pre

dependencies:
  bloc: ^7.2.0-dev.3

  crypto_stats_repository:
    path: packages/crypto_stats_repository
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.2.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.1.2
  flutter_gen_runner: ^3.1.2
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.3.0

flutter:
  uses-material-design: true
  # Enable generation of localized Strings from arb files.
  generate: true
  assets:
    # Add assets from the images directory to the application.
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 800

flutter_gen:
  # By default, the generate files are in `lib/gen/`
  output: lib/generated
