name: crypto_stats_repository
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  crypto_stats_remote_api:
    path: ../crypto_stats_remote_api
  equatable: ^2.0.3
  json_annotation: ^4.1.0

dev_dependencies:
  build_runner: ^2.1.2
  json_serializable: ^5.0.1
  mocktail: ^0.1.4
  test: ^1.17.0
  very_good_analysis: ^2.3.0
